/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import alarma.CargarArchivos;
import alarma.TablaControl;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Dominguez
 */
public class AgregarAlarma extends javax.swing.JFrame {

    /**
     * Creates new form AgregarAlarma
     */
    public AgregarAlarma() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Ingresar Alarma");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jPanel1 = new javax.swing.JPanel();
        btnRegresarAgreAla1 = new javax.swing.JButton();
        btnGuardarAgreAla = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTexto2 = new javax.swing.JLabel();
        lblTexto3 = new javax.swing.JLabel();
        lblTexto4 = new javax.swing.JLabel();
        lblTexto5 = new javax.swing.JLabel();
        lblTexto6 = new javax.swing.JLabel();
        txtNombreAlm = new javax.swing.JTextField();
        cboDia = new javax.swing.JComboBox<>();
        cboHora = new javax.swing.JComboBox<>();
        cboMinuto = new javax.swing.JComboBox<>();
        cboEstado = new javax.swing.JComboBox<>();
        cboSonido = new javax.swing.JComboBox<>();
        lblTexto1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresarAgreAla1.setFont(new java.awt.Font("!!! Handwritingg <3", 0, 15)); // NOI18N
        btnRegresarAgreAla1.setText("REGRESAR");
        btnRegresarAgreAla1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(btnRegresarAgreAla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 120, 30));

        btnGuardarAgreAla.setFont(new java.awt.Font("!!! Handwritingg <3", 0, 15)); // NOI18N
        btnGuardarAgreAla.setText("GUARDAR");
        btnGuardarAgreAla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGuardarAgreAla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAgreAlaActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarAgreAla, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 120, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setOpaque(false);

        lblTexto2.setFont(new java.awt.Font("!CRASS ROOTS OFL", 1, 20)); // NOI18N
        lblTexto2.setForeground(new java.awt.Color(51, 255, 153));
        lblTexto2.setText("Nombre:");

        lblTexto3.setFont(new java.awt.Font("!CRASS ROOTS OFL", 1, 20)); // NOI18N
        lblTexto3.setForeground(new java.awt.Color(51, 255, 153));
        lblTexto3.setText("Hora:");

        lblTexto4.setFont(new java.awt.Font("!CRASS ROOTS OFL", 1, 20)); // NOI18N
        lblTexto4.setForeground(new java.awt.Color(51, 255, 153));
        lblTexto4.setText("Sonido");

        lblTexto5.setFont(new java.awt.Font("!!! Handwritingg <3", 1, 20)); // NOI18N
        lblTexto5.setForeground(new java.awt.Color(51, 255, 153));
        lblTexto5.setText("Estado:");

        lblTexto6.setFont(new java.awt.Font("!CRASS ROOTS OFL", 1, 20)); // NOI18N
        lblTexto6.setForeground(new java.awt.Color(51, 255, 153));
        lblTexto6.setText("Día:");

        txtNombreAlm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cboDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Domingo", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado" }));

        cboHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));

        cboMinuto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activado", "Desactivado" }));
        cboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEstadoActionPerformed(evt);
            }
        });

        cboSonido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AhiVa", "Botella", "Sirena" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTexto4)
                        .addGap(18, 18, 18)
                        .addComponent(cboSonido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTexto5)
                        .addGap(18, 18, 18)
                        .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblTexto3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cboMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblTexto2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombreAlm, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblTexto6)
                                .addGap(18, 18, 18)
                                .addComponent(cboDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(41, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTexto2)
                    .addComponent(txtNombreAlm, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTexto6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTexto3)
                    .addComponent(cboHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTexto4)
                    .addComponent(lblTexto5)
                    .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboSonido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 370, 190));

        lblTexto1.setFont(new java.awt.Font("!!! Handwritingg <3", 1, 36)); // NOI18N
        lblTexto1.setForeground(new java.awt.Color(255, 255, 102));
        lblTexto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/imagen2.jpg"))); // NOI18N
        jPanel1.add(lblTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarAgreAlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAgreAlaActionPerformed


        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarAgreAlaActionPerformed

    private void cboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEstadoActionPerformed


    public JButton getBtnGuardarAgreAla() {
        return btnGuardarAgreAla;
    }

    public void setBtnGuardarAgreAla(JButton btnGuardarAgreAla) {
        this.btnGuardarAgreAla = btnGuardarAgreAla;
    }

    //getter y setter de ingreso texto
    public JButton getBtnRegresarAgreAla1() {
        return btnRegresarAgreAla1;
    }

    public void setBtnRegresarAgreAla1(JButton btnRegresarAgreAla1) {
        this.btnRegresarAgreAla1 = btnRegresarAgreAla1;
    }

    public JComboBox<String> getCboDia() {
        return cboDia;
    }

    public void setCboDia(JComboBox<String> cboDia) {
        this.cboDia = cboDia;
    }

    public JComboBox<String> getCboEstado() {
        return cboEstado;
    }

    public void setCboEstado(JComboBox<String> cboEstado) {
        this.cboEstado = cboEstado;
    }

    public JComboBox<String> getCboHora() {
        return cboHora;
    }

    public void setCboHora(JComboBox<String> cboHora) {
        this.cboHora = cboHora;
    }

    public JComboBox<String> getCboMinuto() {
        return cboMinuto;
    }

    public void setCboMinuto(JComboBox<String> cboMinuto) {
        this.cboMinuto = cboMinuto;
    }

    public JComboBox<String> getCboSonido() {
        return cboSonido;
    }

    public void setCboSonido(JComboBox<String> cboSonido) {
        this.cboSonido = cboSonido;
    }

    public JTextField getTxtNombreAlm() {
        return txtNombreAlm;
    }

    public void setTxtNombreAlm(JTextField txtNombreAlm) {
        this.txtNombreAlm = txtNombreAlm;
    }


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarAgreAla;
    private javax.swing.JButton btnRegresarAgreAla1;
    private javax.swing.JComboBox<String> cboDia;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JComboBox<String> cboHora;
    private javax.swing.JComboBox<String> cboMinuto;
    private javax.swing.JComboBox<String> cboSonido;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private javax.swing.JLabel lblTexto1;
    private javax.swing.JLabel lblTexto2;
    private javax.swing.JLabel lblTexto3;
    private javax.swing.JLabel lblTexto4;
    private javax.swing.JLabel lblTexto5;
    private javax.swing.JLabel lblTexto6;
    private javax.swing.JTextField txtNombreAlm;
    // End of variables declaration//GEN-END:variables
}
