/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import com.toedter.calendar.JCalendar;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Dominguez
 */
public class Edad extends javax.swing.JFrame {

    /**
     * Creates new form Edad
     */
    public Edad() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Ingreso Edad");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        btbEdaSalir = new javax.swing.JButton();
        btbEdaIngreso = new javax.swing.JButton();
        lblTexto3 = new javax.swing.JLabel();
        lblTexto2 = new javax.swing.JLabel();
        lblTexto1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        btbEdaSalir.setFont(new java.awt.Font("!!! Handwritingg <3", 0, 15)); // NOI18N
        btbEdaSalir.setText("Salir");
        btbEdaSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btbEdaSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbEdaSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btbEdaSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 90, 30));

        btbEdaIngreso.setFont(new java.awt.Font("!!! Handwritingg <3", 0, 15)); // NOI18N
        btbEdaIngreso.setText("Ingresar");
        btbEdaIngreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btbEdaIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbEdaIngresoActionPerformed(evt);
            }
        });
        jPanel1.add(btbEdaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 90, 30));

        lblTexto3.setBackground(new java.awt.Color(204, 255, 255));
        lblTexto3.setFont(new java.awt.Font("!!! Handwritingg <3", 1, 18)); // NOI18N
        lblTexto3.setForeground(new java.awt.Color(255, 255, 255));
        lblTexto3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel1.add(lblTexto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 280, 210));

        lblTexto2.setFont(new java.awt.Font("!!! Handwritingg <3", 1, 18)); // NOI18N
        lblTexto2.setForeground(new java.awt.Color(153, 255, 255));
        lblTexto2.setText("Elija su fecha de Nacimiento");
        jPanel1.add(lblTexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 43));

        lblTexto1.setFont(new java.awt.Font("!!! Handwritingg <3", 1, 18)); // NOI18N
        lblTexto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/imagen2.jpg"))); // NOI18N
        jPanel1.add(lblTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbEdaSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbEdaSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btbEdaSalirActionPerformed

    private void btbEdaIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbEdaIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btbEdaIngresoActionPerformed

    

    public JButton getBtbEdaIngreso() {
        return btbEdaIngreso;
    }

    public void setBtbEdaIngreso(JButton btbEdaIngreso) {
        this.btbEdaIngreso = btbEdaIngreso;
    }

    public JButton getBtbEdaSalir() {
        return btbEdaSalir;
    }

    public void setBtbEdaSalir(JButton btbEdaSalir) {
        this.btbEdaSalir = btbEdaSalir;
    }

    public JCalendar getjCalendar1() {
        return jCalendar1;
    }

    public void setjCalendar1(JCalendar jCalendar1) {
        this.jCalendar1 = jCalendar1;
    }




    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbEdaIngreso;
    private javax.swing.JButton btbEdaSalir;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTexto1;
    private javax.swing.JLabel lblTexto2;
    private javax.swing.JLabel lblTexto3;
    // End of variables declaration//GEN-END:variables
}

